BEGIN;

ALTER TABLE incidentes
    ADD COLUMN IF NOT EXISTS fecha_registro DATE,
    ADD COLUMN IF NOT EXISTS fecha_emision DATE,
    ADD COLUMN IF NOT EXISTS lugar VARCHAR(255),
    ADD COLUMN IF NOT EXISTS nombre_apellido VARCHAR(255),
    ADD COLUMN IF NOT EXISTS cargo VARCHAR(150),
    ADD COLUMN IF NOT EXISTS matricula VARCHAR(100),
    ADD COLUMN IF NOT EXISTS dni VARCHAR(50),
    ADD COLUMN IF NOT EXISTS area VARCHAR(150),
    ADD COLUMN IF NOT EXISTS superior_inmediato VARCHAR(255),
    ADD COLUMN IF NOT EXISTS historial TEXT;

COMMIT;
